oS.Init({
PName:[oPeashooter,oSunFlower,oCherryBomb,oWallNut,oPotatoMine,oSnowPea,oChomper,oSplitPea,oJalapeno,oSpikeweed,oRepeater,oTallNut,oPumpkinHead,oSquash,oFlowerPot,oTorchwood,oThreepeater,oGatlingPea,oTwinSunflower,oSpikerock,oFumeShroom,oCoffeeBean,oGloomShroom,oSunShroom,oPuffShroom,oScaredyShroom,oStarfruit,oGarlic],
ZName:[oPeaZombie,oWallNutZombie,oSquashZombie,oJalapenoZombie],
PicArr:["images/interface/background1.jpg"],
backgroundImage:"images/interface/background1.jpg",
CanSelectCard:1,
SunNum:300,
LF:[0,1,1,1,1,0],
StartGameMusic: "MiniGame_ddlc",
ZF:[0,1,1,1,1,1],
LevelName:"小游戏：植物僵尸",
LvlEName:"Zombotany",
LargeWaveFlag:{
10:$("imgFlag3"),
20:$("imgFlag2"),
30:$("imgFlag1")
}
},{
AZ:[
[oPeaZombie,3,1],
[oWallNutZombie,1,1],
[oSqushZombie,1,1],
[oJalapenoZombie,1,1]
],
FlagNum:30,
FlagToSumNum:{
a1:[3,5,9,10,13,15,19,20,23,25,29],
a2:[1,2,3,10,4,5,6,15,7,8,9,25]
},
FlagToMonitor:{
9:[ShowLargeWave,0],
19:[ShowLargeWave,0],
29:[ShowFinalWave,0]
}});
